@startuml
class StateMachine {
    + Update() : void
    + FixedUpdate() : void
    + AnimationEvent(animationEvent:AnimationEvent) : void
    + StartEntryState(state:IState) : void
    + SetState(targetState:IState) : void
    - DoTransition(transition:ITransition) : void
    - GetValidTransition() : ITransition
    - GetOrAddState(state:IState) : StateNode
    + AddTransition(sourceState:IState, targetState:IState, condition:IPredicate) : void
    + AddAnyTransition(targetState:IState, condition:IPredicate) : void
}
class "Dictionary`2"<T1,T2> {
}
class "HashSet`1"<T> {
}
StateMachine --> "_currentState" StateNode
StateMachine o-> "_states<string,StateNode>" "Dictionary`2"
StateMachine o-> "_anyStateTransitions<ITransition>" "HashSet`1"
@enduml
