@startuml
class TurretBuilding {
    - Start() : void
    - FindTarget() : IEnumerator
    - GetTarget() : Transform
    - GetMaxPriorityTarget(colliders:List<Collider2D>) : Transform
    - Shoot() : void
}
Building <|-- TurretBuilding
TurretBuilding --> "firePoint" Transform
TurretBuilding --> "attackSightArea" Collider2D
TurretBuilding --> "_contactFilter2D" ContactFilter2D
TurretBuilding --> "_turretData" TurretBuildingData
@enduml
