@startuml
abstract class SlimeBaseState {
    # <<const>> CrossFadeTime : float = 0.1f
    # {static} <<readonly>> WalkingAnimHash : int
    # {static} <<readonly>> ChasingAnimHash : int
    # {static} <<readonly>> DyingAnimHash : int
    # {static} <<readonly>> TakingDamageAnimHash : int
    - {static} <<readonly>> VelX : int
    - {static} <<readonly>> VelY : int
    + {abstract} Name : string <<get>>
    # SlimeBaseState(slime:Slime, navMeshAgent:NavMeshAgent, animator:Animator)
    + <<virtual>> OnEnter() : void
    + <<virtual>> OnExit() : void
    + <<virtual>> OnUpdate() : void
    + <<virtual>> OnFixedUpdate() : void
    + <<virtual>> OnAnimationEvent(animationEvent:AnimationEvent) : void
}
IState <|-- SlimeBaseState
SlimeBaseState --> "Slime" Slime
SlimeBaseState --> "NavMeshAgent" NavMeshAgent
SlimeBaseState --> "Animator" Animator
@enduml
