@startuml
class EnemyWavesManager {
    - _curWaveIndex : int
    - <<const>> Radius : float = 35
    - _delayMultiplier : float
    - _enemiesCountMultiplier : float
    + SpawnNewWave() : void
    - GetWaveToSpawn() : EnemyWaveData
    - CalculateMultipliers() : void
    - SpawnWave() : IEnumerator
    - SpawnChunk(chunkInfo:EnemyWaveData.EnemyWaveChunk) : void
    - SpawnEnemyOnCircle(enemyToSpawn:GameObject) : void
}
MonoBehaviour <|-- EnemyWavesManager
@enduml
