@startuml
class HealthBar {
    - Start() : void
    + ChangeHp(_:HitInfo?, remainingHealth:int) : void
    - SetHealth(health:int) : void
}
MonoBehaviour <|-- HealthBar
HealthBar --> "playerHealthController" HealthController
HealthBar --> "slider" Slider
HealthBar --> "fillImage" Image
HealthBar --> "gradient" Gradient
@enduml
