@startuml
class TilemapManager {
    + AddObject(building:Building, position:Vector2Int) : bool
    + RemoveObject(building:Building, position:Vector2Int) : void
    + GetBuildingsAt(position:Vector2Int) : List<Building>
    + GetBuildingAt(position:Vector2Int) : Building
    + HasBuildingAt(position:Vector2Int) : bool
}
class "Dictionary`2"<T1,T2> {
}
MonoBehaviour <|-- TilemapManager
TilemapManager o-> "gridBuildings<Vector2Int,List<Building>>" "Dictionary`2"
@enduml
