@startuml
class DayNightManager {
    - dayLength : float = 60
    - nightLength : float = 30
    + IsDay : bool <<get>> = true
    - _currentTime : float
    - DaysNumber : int <<get>> <<set>> = 1
    - Update() : void
}
MonoBehaviour <|-- DayNightManager
DayNightManager --> "sun" Light2D
DayNightManager --> "dayColor" Color
DayNightManager --> "nightColor" Color
DayNightManager --> "onDayStart" UnityEvent
DayNightManager --> "onNightStart" UnityEvent
@enduml
