@startuml
class ButtonSoundController {
    + OnPointerEnter(eventData:PointerEventData) : void
    + OnPointerDown(eventData:PointerEventData) : void
}
MonoBehaviour <|-- ButtonSoundController
IPointerEnterHandler <|-- ButtonSoundController
IPointerDownHandler <|-- ButtonSoundController
@enduml
