@startuml
class HealItem {
    - healAmount : int
    - Update() : void
    + SetActive(active:bool) : void
}
MonoBehaviour <|-- HealItem
ILogic <|-- HealItem
HealItem --> "item" InventoryItem
@enduml
