@startuml
class Hoe {
    # <<override>> Start() : void
    # <<override>> UseItem(cursorPosition:Vector3Int) : void
    # <<override>> CheckIfCanUseItem() : bool
    - FindTargetsAtCursor() : void
    - IsPlayerWithinRange() : bool
    - CheckForObstructions() : bool
}
WorldCursor <|-- Hoe
Hoe --> "_selectedCrop" Crop
Hoe --> "_selectedSeedbed" Seedbed
Hoe --> "seedbedPrefab" GameObject
Hoe --> "data" HoeData
Hoe --> "animatorOverrideController" AnimatorOverrideController
Hoe --> "_tilemapManager" TilemapManager
@enduml
