@startuml
class SlimeAttackingState {
    + <<override>> Name : string <<get>>
    - _lastAttackTime : float
    + SlimeAttackingState(slime:Slime, navMeshAgent:NavMeshAgent, animator:Animator, attackArea:Collider2D, contactFilter2D:ContactFilter2D)
    + <<override>> OnEnter() : void
    + <<override>> OnExit() : void
    + <<override>> OnAnimationEvent(animationEvent:AnimationEvent) : void
    - Attack() : void
    - WalkToTarget() : IEnumerator
}
SlimeBaseState <|-- SlimeAttackingState
SlimeAttackingState --> "_attackArea" Collider2D
SlimeAttackingState --> "_contactFilter2D" ContactFilter2D
SlimeAttackingState --> "walkingToTargetCoroutine" Coroutine
@enduml
