@startuml
class SlimeTakingDamageState {
    + <<override>> Name : string <<get>>
    - <<const>> KnockBackDistance : float = 1f
    - <<const>> KnockBackSpeed : float = 7f
    - {static} <<readonly>> HitX : int
    - {static} <<readonly>> HitY : int
    + SlimeTakingDamageState(slime:Slime, navMeshAgent:NavMeshAgent, animator:Animator)
    + <<override>> OnEnter() : void
    + <<override>> OnUpdate() : void
    + <<override>> OnAnimationEvent(animationEvent:AnimationEvent) : void
}
SlimeBaseState <|-- SlimeTakingDamageState
SlimeTakingDamageState --> "knockBackPosition" Vector2
SlimeTakingDamageState --> "HitInfo" HitInfo
@enduml
