@startuml
abstract class PlayerBaseState {
    # <<const>> CrossFadeTime : float = 0f
    # {static} <<readonly>> WateringAnimHash : int
    # {static} <<readonly>> AttackingAnimHash : int
    # {static} <<readonly>> WeedingAnimHash : int
    # {static} <<readonly>> IdleAnimHash : int
    # {static} <<readonly>> MovementAnimHash : int
    # {static} <<readonly>> TakingDamageAnimHash : int
    # {static} <<readonly>> DyingAnimHash : int
    # {static} <<readonly>> UseToolAnimHash : int
    # {static} <<readonly>> IdleToolAnimHash : int
    - {static} <<readonly>> LookDirXHash : int
    - {static} <<readonly>> LookDirYHash : int
    - {static} <<readonly>> VelX : int
    - {static} <<readonly>> VelY : int
    + {abstract} Name : string <<get>>
    # PlayerBaseState(playerController:PlayerController, animator:Animator, toolAnimator:Animator, rigidbody2D:Rigidbody2D)
    + <<virtual>> OnEnter() : void
    + <<virtual>> OnExit() : void
    + <<virtual>> OnUpdate() : void
    - UpdateAnimationParameters() : void
    + <<virtual>> OnFixedUpdate() : void
    + <<virtual>> OnAnimationEvent(animationEvent:AnimationEvent) : void
}
IState <|-- PlayerBaseState
PlayerBaseState --> "PlayerController" PlayerController
PlayerBaseState --> "Rigidbody2D" Rigidbody2D
PlayerBaseState --> "Animator" Animator
PlayerBaseState --> "ToolAnimator" Animator
@enduml
