@startuml
class PlayerTakingDamageState {
    + <<override>> Name : string <<get>>
    - <<const>> KnockBackDistance : float = 1f
    - <<const>> KnockBackSpeed : float = 7f
    - {static} <<readonly>> HitX : int
    - {static} <<readonly>> HitY : int
    + PlayerTakingDamageState(playerController:PlayerController, animator:Animator, toolAnimator:Animator, rigidbody2D:Rigidbody2D)
    + <<override>> OnEnter() : void
    - SetupHitDirectionForAnimation() : void
    - CalculateKnockbackPosition() : void
    + <<override>> OnUpdate() : void
    + <<override>> OnAnimationEvent(animationEvent:AnimationEvent) : void
}
PlayerBaseState <|-- PlayerTakingDamageState
PlayerTakingDamageState --> "knockBackPosition" Vector2
PlayerTakingDamageState --> "HitInfo" HitInfo
@enduml
