@startuml
class AudioManager {
    - sfxSourcesCount : int = 10
    - _currentMusicGroup : string
    - Awake() : void
    - OnDestroy() : void
    - InitializeAudioSources() : void
    - OnSceneLoaded(scene:Scene, mode:LoadSceneMode) : void
    + PlayMusic(groupName:string) : void
    + StopMusic() : void
    + PauseMusic() : void
    + ResumeMusic() : void
    + PlaySound(groupName:string, position:Vector3?) : void
    + PlayLoopingSound(groupName:string, position:Vector3?) : void
    + StopLoopingSound(groupName:string) : void
    + StopAllLoopingSounds() : void
    - GetAvailableSfxSource() : AudioSource
    + PlayFootstepSound(position:Vector3) : void
    + PlayPlayerHurtSound(position:Vector3) : void
    + PlaySwordSwingSound(position:Vector3) : void
    + PlayWateringCanSound(position:Vector3) : void
    + PlayFillWateringCanSound(position:Vector3) : void
    + PlayPluggingDirtSound(position:Vector3) : void
    + PlaySlimeJumpSound(position:Vector3) : void
    + PlaySlimeAttackSound(position:Vector3) : void
    + PlaySlimeDeathSound(position:Vector3) : void
    + PlaySlimeTakingDamageSound(position:Vector3) : void
    + StartRainSound() : void
    + StopRainSound() : void
}
class "List`1"<T> {
}
class "Dictionary`2"<T1,T2> {
}
MonoBehaviour <|-- AudioManager
AudioManager --> "Instance" AudioManager
AudioManager --> "audioData" AudioData
AudioManager --> "musicSource" AudioSource
AudioManager --> "ambienceSource" AudioSource
AudioManager o-> "_sfxSources<AudioSource>" "List`1"
AudioManager o-> "_loopingSounds<string,AudioSource>" "Dictionary`2"
@enduml
