@startuml
class ShopItem {
    + isSelling : bool <<get>>
    - _price : int
    - _startPrice : int
    - _itemCount : int
    - _maxItemCount : int
    - <<const>> MinDecreasePriceMultiplier : float = 0.8f
    - <<const>> MaxIncreasePriceMultiplier : float = 1.2f
    - _sellRow : int
    - _wasSoldLastDay : bool
    - _isMouseOver : bool
    - <<const>> ItemCountChangeInterval : float = 0.1f
    - _itemCountChangeTimer : float
    - Awake() : void
    - Update() : void
    - HandleKeyboardInput() : void
    + UpdateUI() : void
    - UpdateData() : void
    - UpdateSellingData() : void
    - UpdateBuyingData() : void
    + ShopButtonAction() : void
    - Buy() : void
    - SpawnPurchasedItems() : void
    - Sell() : void
    + OnScroll(eventData:PointerEventData) : void
    - OnDayChange() : void
    - UpdatePriceForNewDay() : void
    - GetSpriteAssetText(text:string) : string
    - OnDestroy() : void
    + OnPointerEnter(_:PointerEventData) : void
    + OnPointerExit(_:PointerEventData) : void
    + OnDisable() : void
}
MonoBehaviour <|-- ShopItem
IScrollHandler <|-- ShopItem
IPointerEnterHandler <|-- ShopItem
IPointerExitHandler <|-- ShopItem
ShopItem --> "shop" Shop
ShopItem --> "itemData" ShopItemData
ShopItem --> "buySellButton" Button
ShopItem --> "itemName" TextMeshProUGUI
ShopItem --> "priceText" TextMeshProUGUI
ShopItem --> "itemCountText" TextMeshProUGUI
@enduml
