@startuml
class Building {
    # <<virtual>> Awake() : void
    # <<virtual>> OnDestroy() : void
    + <<virtual>> Die() : void
    # <<virtual>> GetPosition() : Vector2Int
}
MonoBehaviour <|-- Building
Building --> "buildingData" BuildingData
Building --> "TilemapManager" TilemapManager
Building --> "Position" Vector2Int
@enduml
