@startuml
class InventorySlot {
    + indexInInventory : int <<get>> <<set>>
    - Awake() : void
    + UpdateUI() : void
    - ShowEmptySlot() : void
    - ShowItemInSlot() : void
    + OnPointerDown(eventData:PointerEventData) : void
    - StartDragging() : void
    + OnPointerUp(eventData:PointerEventData) : void
    - EndDragging() : void
    - HandleItemTransfer(otherSlot:InventorySlot) : void
    - MoveItemToEmptySlot(destinationSlot:InventorySlot) : void
    - StackWithSameItem(destinationSlot:InventorySlot) : void
    - SwapWithDifferentItem(otherSlot:InventorySlot) : void
    + RemoveFromSlot(quantityToRemove:int) : bool
}
MonoBehaviour <|-- InventorySlot
IPointerDownHandler <|-- InventorySlot
IPointerUpHandler <|-- InventorySlot
InventorySlot --> "inventory" Inventory
InventorySlot --> "itemIcon" Image
InventorySlot --> "itemQuantityText" TextMeshProUGUI
InventorySlot --> "canvasGroup" CanvasGroup
InventorySlot --> "slotBorder" Image
InventorySlot --> "item" InventoryItem
@enduml
