@startuml
class Inventory {
    + activeItemIndex : int <<get>>
    + dragItemAlpha : float = 0.6f
    - Awake() : void
    - Update() : void
    - SetupInventorySlotsIndices() : void
    - HandleMouseScrollSelection() : void
    - HandleNumberKeySelection() : void
    + AddItems(item:InventoryItem, quantity:int) : void
    - TryStackWithExistingItems(item:InventoryItem, quantity:int) : int
    - AddItemToEmptySlot(item:InventoryItem, quantity:int) : void
    + DropItem(item:InventoryItem) : void
    - ChangeActiveItem(index:int) : void
    + SetItemLogicActive(isActive:bool) : void
    + SetItemLogicActive(index:int, isActive:bool) : void
    + RemoveItems(itemName:string, quantity:int) : void
    + ChangeItemsCount(itemName:string, count:int) : void
}
class "List`1"<T> {
}
class "Dictionary`2"<T1,T2> {
}
MonoBehaviour <|-- Inventory
Inventory --> "inventorySlots<InventorySlot>" "List`1"
Inventory o-> "ItemQuantities<string,int>" "Dictionary`2"
Inventory --> "CurrentActiveItem" InventoryItem
@enduml
